### ISSUE TITLE
/timeseries_hr/recoveries file available? 

### ISSUE THREAD

**Issue by joshjpark** [ccodwg/Covid19Canada#24]
Firstly, thank you for maintaining the spreadsheet and this repo.

I was looking at recoveries data in Covid19Canada/timeseries_hr/ in particular. Would that be available as well?

I am creating a web-app providing info for each province & regions and I am missing # of recoveries for each region ATM. Thanks again!

**Comment by jeanpaulrsoucy** [comment]
Hi, the recovering time series is available here:

**Comment by jeanpaulrsoucy** [comment]
Hi, we don't track recoveries at the health region level. Only the province level. The reason is that most provinces do not report this at the region level, only the provincial level.

For Ontario, you can find individual-level recovery data here:

https://data.ontario.ca/dataset/confirmed-positive-cases-of-covid-19-in-ontario/resource/455fd63b-603d-4608-8216-7d8647f43350

But be aware the date variable is different from the report date that you will find in most places.

Alberta has data too (see data export tab):

https://covid19stats.alberta.ca/
