### ISSUE TITLE
Geocoding for each health region

### ISSUE THREAD

**Issue by donaldzou** [ccodwg/Covid19Canada#25]
Hi, I'm using Leaflet to geo locate the health region, but there's some health regoin i cannot locate, do you guys have any thoughts on that? I'm using Mapbox geocoding

**Comment by jeanpaulrsoucy** [comment]
We use what are reported by the provinces, which for a few provinces don't correspond to health regions published by StatCan. For example, Sask. amalgamated all their health regions into one but still reports results with some granularity (North, Saskatoon, etc.)---but these do not correspond to the health region boundary files provided by StatCan. That's one reason we use points rather than polygons in our case map.

**Comment by donaldzou** [comment]
Hi, I'm using points to locate the health region too, but for example in Ontario there is "Kingston Frontenac Lennox" for a health region, but I could not geocoding that location because there isn't an exact place for that. Do you have solution for that problem? Sorry for asking to much :)

**Comment by sitrucp** [comment]
I created mapping file from Statscan to health authority boundary names https://github.com/sitrucp/canada_covid_health_regions/blob/master/health_regions_lookup.csv

**Comment by donaldzou** [comment]
@sitrucp Thank you soooo much for that, I tried to geolocate it by names, but some of them isn't correct in some map service, but i can just use your json file. Thank you so much
