### ISSUE TITLE
Tests-performed or people-tested?

### ISSUE THREAD

**Issue by johanley** [ccodwg/Covid19Canada#29]
What exactly do the testing numbers mean?

Are you reporting on **people-tested**, or **tests-performed**? I don't see that specified anywhere.

When I look at the government source data, it seems to be a mixed bag.
Some jurisdictions report on _both_ tests-performed and people-tested, but most don't.

Examples:
Tests-performed: BC, MB
People-tested: QC, NL

**Comment by jeanpaulrsoucy** [comment]
As you pointed out, it depends on the province. The [Globe & Mail](https://www.theglobeandmail.com/canada/article-coronavirus-cases-canada-world-map-explainer/) has a list of which is which.

![Screenshot_2020-05-09 How many coronavirus cases are there in Canada, by province, and worldwide The latest maps and charts](https://user-images.githubusercontent.com/31170087/81463828-a51ee080-918a-11ea-8f80-24763438a94d.png)

Of course, at least one province (Ontario) switched from people tested to tests performed midway through. We use whichever is the main reported number for the province, since as far as we know we don't have both numbers for all provinces.

We'll be adding a plot to distinguish the two soon. We'll also add it to the methods tab.

**Comment by jeanpaulrsoucy** [comment]
PHAC now reporting a time series of "individuals tested": https://www.canada.ca/en/public-health/services/diseases/2019-novel-coronavirus-infection.html

With the following caveat: "Note: Provincial/territorial (PT) data reported on their websites should be used if there are discrepancies. This can be due to lags, differing reporting cut-offs, or changes in lab testing criteria. For PTs that report the number of tests completed, a formula is used to estimate the number of individuals tested."
