### ISSUE TITLE
code for Health regions

### ISSUE THREAD

**Issue by hgw0610209** [ccodwg/Covid19Canada#30]
Hi, 
Impressive work! Just wonder is it possible to add the HR_UID to each health region?
Seems that the health regions names from different sources (e.g., shapefile) could be very different. 

thanks,

Guowen

**Comment by jeanpaulrsoucy** [comment]
Hi Guowen,

For some places, the boundaries that cases are reported at are not in agreement with those provided in the StatCan HR boundary file (e.g., Sask amalgamated into a single health authority and report cases using different regions than those in the HR boundary file). Otherwise, we use the English names as provided in the HR boundary file and the centroids of these regions (with a few exceptions).
