### ISSUE TITLE
BC cases for reporting gaps

### ISSUE THREAD

**Issue by gauss256** [ccodwg/Covid19Canada#36]
The file `cases_timeseries_prov.csv` could be improved for BC (and perhaps other provinces). The issue is that the province does not issue a report every day: there are gaps. The first report after a gap provides the case counts for each of the days during the gap, as well as the current day.

The problem is that the cases for the gap days are recorded as 0 in the database, and all the cases that occurred during the gap are lumped together into one number on the day of the next report.

Example (from today): If the case counts on (Saturday, Sunday, Monday) are (10, 6, 16) but there was no report issued on Saturday and Sunday, the database values are recorded as (0, 0, 32). It would be better if the cases were properly attributed to the correct days, to be consistent with the official reports.

If the current team does not have the ability to implement that procedure, I would be willing to make those updates, since I am tracking these numbers for my own purposes.

**Comment by hdsheena** [comment]
We also have data on things like age, sex and linking of cases to existing outbreaks/travel/etc that is released monthly by BCCDC. finding a way to fit that into this data would make it more useful.

**Comment by ishaberry** [comment]
Hi There-- thanks for your comment.

To ensure consistency across provinces and over time-- we use public report date for all cases, as opposed to the internal report dates within provinces/health regions. The reason for this is because old cases are revised and updated constantly by Provinces -- including cases being added/removed months later. However, the date released by different provinces is not standardized-- some have internal report dates, some have 'accurate episode date', some have test date, etc. To ensure consistency we use public report date as this is stable over time and amongst provinces. This allows data users (and we encourage all users to do so!) to decide how they want to account for reporting lags in a standardized way as well.

We are hoping to link our dataset with that of BCCDC, AHS, and ON Ministry-- but given that none of the dates match up in a standardized way this is difficult. We are currently working on developing a probabilistic linkage algorithm to link these datasets while preserving our data structure. More on this coming soon!

**Comment by hdsheena** [comment]
Let me know if I can help!
