### ISSUE TITLE
Ontario data discrepancy

### ISSUE THREAD

**Issue by gauss256** [ccodwg/Covid19Canada#37]
The numbers for `cases` and `cumulative_cases` for Ontario don't match those on the [government website](https://covid-19.ontario.ca/index.html). Why is that?

**Comment by jeanpaulrsoucy** [comment]
The Ontario Ministry of Health's numbers are delayed compared to those released on the websites of individual health units. As of April 1, we use data reported by individual health units. Please see the "about the data" tab here:

https://art-bd.shinyapps.io/covid19canada/

We should probably mirror this info on the data repo as well.

**Comment by veev** [comment]
@jeanpaulrsoucy I'm also seeing a discrepancy between the numbers for Peel cases and cumulative_cases and what is available on [Region of Peel's PHU site](https://www.peelregion.ca/coronavirus/case-status/). Can you point me to the place where you got the numbers for Peel?

**Comment by jeanpaulrsoucy** [comment]
@veev The Peel dashboard seems to be updated only every couple of weeks now, so we're relying on the daily case numbers in the table at the page you linked (https://www.peelregion.ca/coronavirus/case-status/).

Dashboard: https://experience.arcgis.com/experience/e21b45996d0b4f77a045447ff65b9831 [last update: July 17, 2020; next update: July 31, 2020]

I assume you're referring to the cumulative numbers given once a week in the weekly reports.

Latest report (July 24, 2020): https://www.peelregion.ca/health/professionals/pdfs/COVID-19/epi-update-20-24-07.pdf

Seems their cumulative number is a bit lower than ours...6,939 vs our 6,973 for July 23.

I suspect this is either due to syncing with iPHIS (which is usually a bit behind) or because they have silently removed some old cases (or both). Sometime PHUs/provinces are very specific about removing old cases, but not all of them.

Without a revised daily case time series from Peel (based on public report date), there's not much we can do to correct this, unfortunately. We could arbitrarily remove cases on the day of the weekly reports to match cumulative totals based on the weekly report, I guess. But then the daily incidence will be very wrong once per week. Luckily the overall discrepancy is very small.

**Comment by jeanpaulrsoucy** [comment]
The daily numbers do line up. Peel Site / Our Dataset

July 23: 21 / July 24: 21
July 24: 19 / July 25: 19
July 25: 12 / July 26: 12
July 26: 16 / July 27: 16

Keeping in mind that Peel labels data released today as being from yesterday, which accounts for the 1-day lag.

**Comment by veev** [comment]
@jeanpaulrsoucy Thank you so much for these details. We were getting historical data mainly from the Region of Peel dashboard, but it looks like the most accurate numbers go into the weekly report. Also, great to know about the one day offset between their data and yours, this is very helpful. Data for July seems to be aligned like you wrote. For values in May, we are still seeing some discrepancies. If you look at the dashboard on this [page](https://www.peelregion.ca/coronavirus/case-status/) (blue bar chart): 

![image](https://user-images.githubusercontent.com/626371/88724187-14580100-d0f8-11ea-965d-7b0dfadcf4d2.png)

They are reporting cases on May 1st at 95. In your data, reported cases on May 1st are 55, and on May 2nd are 63. Thank you for taking the time to dig into this, it might be that the data feeding into their dashboard is not reliable, but the weekly reports are. It seems like they are in the process of updating their dashboard and data repository as well, so hopefully some of these discrepancies will be addressed.

Appreciate your timely and detailed response!

**Comment by jeanpaulrsoucy** [comment]
This one comes down to the slightly misleading name of "report date" in iPHIS. Contrary to the name, this is NOT the date a case was reported to the public, rather it is the date a the laboratory reported to the result to the Public Health Unit (likely by fax...). You can find this definition in the Ontario iPHIS data dictionary here: https://data.ontario.ca/dataset/confirmed-positive-cases-of-covid-19-in-ontario/resource/a2ea0536-1eae-4a17-aa04-e5a1ab89ca9a?inner_span=True

Many cases will be entered into the system (and then publicly reported) the same day they are received from the laboratory, but certainly not all - there can sometimes be a multi-day delay. Unfortunately, date the case was entered into the system is not included in the public iPHIS database above (although it does exist in the system).

What this means is that some cases are backdated on the date they are publicly reported. For example, if 15 cases are announced, 11 of them may have the same report day as the date of announcement, 3 may have a report date of 1 day earlier, and 1 may have a report date of 2 days earlier. But in our system, we use date of public report---meaning all 15 of these cases would count for today, and none of them would be backdated. This is to keep things consistent between different provinces/PHUs.

I hope this makes sense!

**Comment by jeanpaulrsoucy** [comment]
I should also note that the various dates in the Ontario iPHIS system will sometimes be modified after they are reported, which further complicates things.

Regardless, you should be able to reproduce the time series you linked using the Ontario confirmed cases dataset:

https://data.ontario.ca/dataset/confirmed-positive-cases-of-covid-19-in-ontario/resource/455fd63b-603d-4608-8216-7d8647f43350?inner_span=True

Just be aware that the most recent few days of cases will be lower than expected due to backdating.
