### ISSUE TITLE
Recovery numbers for Ontario are lagging as case numbers are from PHUs

### ISSUE THREAD

**Issue by advaithasabnis** [ccodwg/Covid19Canada#38]
Thanks for curating this dataset and all your efforts!

I noticed that the number of recoveries is equal to that reported by Ontario (which is lagging) while case numbers are from individual PHUs (which are more recent). This makes it seem like Ontario has a larger number of active cases than it actually does.

For example, on July 28th, 21:00
According to this data: # of active cases is 3,400 with 34,567 recovered.
If you sum up recoveries from individual PHUs they come to around 36,200 meaning in reality active cases is almost half of that.

Would it be possible for you to source recoveries from individual PHUs as well?

**Comment by ishaberry** [comment]
Hi There-- thanks for your message!

At the time that we switched over to reporting cases from PHUs (on April 1), not all PHUs were providing information on recoveries so we had to stick with the Ministry number. Of course, there have been many updates to PHU websites since that time. We will have a look through to confirm that all PHUs are now reporting recovery numbers on a daily basis (I believe the dashboard in Peel is still getting updated, so we'll keep an eye on that) and if so we can definitely look to switch over soon.

Thanks again!

**Comment by advaithasabnis** [comment]
Sounds good! I think all PHUs now have recovery data but I'm not a 100% sure (except Peel which is updating yea). For example, https://coronavirus.1point3acres.com/en gets recovery data from each PHU I believe and then the active cases is more in line with the true number.
