### ISSUE TITLE
Ontario Significant Discrepancies in cases.csv

### ISSUE THREAD

**Issue by beshtoev** [ccodwg/Covid19Canada#39]
Thank you very much for the work you do. Multiple provinces have some minor variances to official Canadian numbers due to timing. And this is fine. When it comes to Ontario, your data set shows almost 2,000 cases higher than Ontario/Canada officially reported to date. Please see the attached excel with COVID19 cases cross-validation. It is definitely not due to the timing, as the gap started a few months ago and keeps on widening. I am trying to understand the nature of the difference that is unique to Ontario. If you think the data need to be fixed, I can help. I am also happy to jump on a call to discuss.

[Variances in COVID19 Daily New Cases Reporting by Province.xlsx](https://github.com/ishaberry/Covid19Canada/files/5071662/Variances.in.COVID19.Daily.New.Cases.Reporting.by.Province.xlsx)

**Comment by ishaberry** [comment]
Hi There--Thanks for your comment. 

On April 1 we switched to using numbers reported by each PHU as opposed to the Ontario Ministry dataset because the Ministry numbers tend to have significant lags. As a result, the numbers we report tend to be higher than those from other sources-- but they will align with what is released daily by each PHU. We explain this further in our "About the Data" section on our dashboard-- https://art-bd.shinyapps.io/covid19canada/

Hope that helps answer your question!
