### ISSUE TITLE
Ontario data

### ISSUE THREAD

**Issue by esklarski** [ccodwg/Covid19Canada#40]
I have switched the provincial/territorial charts on my site [link](https://esklarski.github.io/canada.covid19/) fully to your datasets, and I am noticing an oddity with the Ontario data. At first I thought it was a problem of the Canada data as the numbers here differ greatly from the John Hopkins data (they report about 2000 fewer cumulative cases), but on drilling down all the provinces seem fine except Ontario.

As of this morning 2020/08/15 1100h Pacific, the Ontario Government is reporting 40,565 cases
![Ontario ca](https://user-images.githubusercontent.com/55821817/90318822-007a1080-dee8-11ea-9afc-1c0608bdcbcd.jpg)

While the data here reports 42288 cases. While comparing to: [COVID-19 Case Data (Ontario.ca)](https://covid-19.ontario.ca/data), I see the data starts diverging on April 01, 2020. I am curious if there is a known reason for this difference?

**Comment by gauss256** [comment]
There's been a few issues about this. See #39 for example.

**Comment by esklarski** [comment]
My apologies, I forgot to look through closed issues.

I see that explains the April 2 data, but does that not imply that the Health Ministry is under-reporting cases for 4 months now? And significantly?

**Comment by ishaberry** [comment]
Hi there-- we have a few explanations for this in the closed issues. But overall -- our numbers are pulled directly from the individual Public Health Units for Ontario (a list of our go-to sources is available [here](https://docs.google.com/spreadsheets/d/1Z-TIz2YzQW9NInFB-iGHuv0l1FMYA36otT7TuKjNRz8/edit)). There are significant delays/lags/changes within the ministry dataset, which is why we rely on the PHUs. We will be posting an FAQ section soon to help answer these questions. Hope this helps!

**Comment by giiba** [comment]
Thanks for the patience. I'm just surprised as it means most other datasets out there are under reporting Canada's case counts, because of the Ontario Health Ministry's bad data.

I thank all involved for this effort to collect good data in Canada.

**Comment by jeanpaulrsoucy** [comment]
Ontario is switching to a new data system right now...hopefully will reduce discrepancies in the future!
