### ISSUE TITLE
discrepancy in jan 9 Ontario avaccine numbers

### ISSUE THREAD

**Issue by titaniumbones** [ccodwg/Covid19Canada#61]
The Star shows admin vaccine numbers over 15000 on Jan 9, 2020, but this dataset has 1261 for that date. They don't give a link for their data source but say "The data for Ontario's shots given comes from the provincial government". No idea who's right, just flagging the discrepancy.  Their total matches cumulative_avaccine so it does look a bit fishy, but otoh 1261 sounds quite low compared to its neighbours. 

https://www.thestar.com/news/canada/2021/01/07/covid-19-vaccine-tracker-tracing-every-dose-of-the-coronavirus-vaccine-administered-in-canada.html

**Comment by titaniumbones** [comment]
looks like the star is pulling numbers from https://data.ontario.ca/dataset/covid-19-vaccine-data-in-ontario 

This dataset is a little odd - - their cumulative numbers don't match their dailies, and the offset shifts over time.

**Comment by ishaberry** [comment]
HI there-- this is due to differences in which sources are being used. We tend to use the OHA dataset (which reports for the day of), while the official ontario dataset is usually 1 day behind-- so on days that OHA does not release a situation report we use that.  THis causes bumps on weekends because OHA just announced they are not releasing sitreps on weekends anymore, so we'll be using the ON vaccine data source. We will be looking into aligning these sources

**Comment by ishaberry** [comment]
You can see the discrepancy between the sources (based on the timeframe being evaluated) here: 
OHA: https://www.oha.com/news/updates-on-the-novel-coronavirus
Ontario official data: https://data.ontario.ca/dataset/covid-19-vaccine-data-in-ontario/resource/8a89caa9-511c-4568-af89-7f2174b4378c
