### ISSUE TITLE
Add data on number of people fully vaccinated

### ISSUE THREAD

**Issue by jeanpaulrsoucy** [ccodwg/Covid19Canada#62]
We have been tracking the number of people fully vaccinated (in this case, received both doses of either Pfizer or Moderna). This metric is now available for most but not all provinces. Dates when the data are not available for a particular province will be indicated by NA.

- [x] Add `vaccine_fully_vaccinated.csv` to root directory
- [x] Update script `data_update.R` to convert `vaccine_fully_vaccinated.csv` to time series data
- [x] Add documentation regarding which provinces and territories are reported data on the number of people fully vaccinated

**Comment by jeanpaulrsoucy** [comment]
How to handle provinces not yet reporting this value? Currently, they are just filled with 0s, like we do with early unavailable data on testing and recovered. However, this may be misleading. We have a few options:

* Document which provinces are not reporting this metric and hope people read this before interpreting it
* Filter out these provinces from the cumulative and time series CSVs, although this would require some special code

Doing both is probably optimal.

**Comment by jtracey** [comment]
Ontario just changed their columns, so that what was previously implied to be the number of people fully vaccinated, is now "total doses in fully vaccinated individuals", and a new column has been added for "total individuals fully vaccinated", which seems to just be the prior's value divided by two, rounded up.
