### ISSUE TITLE
Additional details on the cases (symptomatic vs asymptomatic, and unvaccinated/partially/fully vaccinated)

### ISSUE THREAD

**Issue by danielnguyen** [ccodwg/Covid19Canada#80]
Are there any possibilities of adding further breakdown of the daily cases, such as percentage of symptomatic/asymptomatic, and percentage of unvaccinated/partially vaccinated/fully vaccinated?

I'm not sure about other provinces, but Public Health Ontario seems to track those metrics: https://www.publichealthontario.ca/-/media/documents/ncov/epi/covid-19-epi-confirmed-cases-post-vaccination.pdf

Thanks!

**Comment by danielnguyen** [comment]
Hi @jeanpaulrsoucy , not sure if this information is available, and if they can be exposed via the APIs?

Monitoring the daily new cases breakdown by vaccinated/partially/unvaccinated would be tremendously helpful in seeing whether or not we might be heading towards a similar situation as in Israel...

Potentially a breakdown in which variants they are would be powerful information as well.

Thank you!

**Comment by jeanpaulrsoucy** [comment]
Hi @danielnguyen, as far as I am aware, this information is not generally available for most provinces (at least not in an easily accessible or regularly updated way). Of course there are exceptions (Ontario, Alberta) but these are really province-specific datasets.

PHAC also has a [national-level dataset](https://health-infobase.canada.ca/covid-19/epidemiological-summary-covid-19-cases.html#a9) on this although it is poorly contextualized (no age or time period breakdown).

That being said, I am certainly ARCHIVING all of the data I find on this subject, so that time series may be reconstructed at a later date. If you find any useful datasets please open an issue at [Covid19CanadaArchive](https://github.com/ccodwg/Covid19CanadaArchive).
