### ISSUE TITLE
Question about Alberta-Central health region case numbers from 05-02-2020 to 06-09-2020

### ISSUE THREAD

**Issue by manisci** [ccodwg/Covid19Canada#86]
Hi,

I was looking at the number of new cases for the central region of Alberta and it seems the number of new cases for the whole interval of 05-02-2020 to 06-09-2020 is zero, even though for the previous 52 days, the average number of new cases is 1.67 each day. I was wondering if there was an explanation for this, or if this is some imperfection in the data that cannot be dealt with. 

Thank you.
Mani Sotoodeh

**Comment by jeanpaulrsoucy** [comment]
Hi Mani,

I looked into this today.

On 2020-06-07, we had 87 cases for AB - Central on 2020-05-01 and 97 on 2020-06-07.

https://github.com/ccodwg/Covid19Canada/blob/2249dc11bb09f3a0e431407a1e1ec3b167584337/timeseries_hr/cases_timeseries_hr.csv

On 2020-07-08, we had 87 cases for AB - Central on 2020-05-01 and 87 on 2020-06-08.

https://github.com/ccodwg/Covid19Canada/blob/6721240034e5106035ace2be8b3b66d3ec356c4a/timeseries_hr/cases_timeseries_hr.csv

So what happened? The diff on the individual-level case dataset provides the answer:

https://github.com/ccodwg/Covid19Canada/commit/6721240034e5106035ace2be8b3b66d3ec356c4a#diff-f299c7ed032ed6017f03b570d645235760239ba8455e86ac78da955e29431910

"08-06-2020: 10 fewer cases in Central. Cases redistributed accordingly."

Our policy at the time was to always match the provided _cumulative_ totals. If cases were removed from a region (evidently 10 cases were removed the cumulative total for Central on 2020-06-08), our policy was to remove the most recent 10 cases added in order to accommodate the new cumulative total (since we had no way of knowing which dates the cases were removed on). Unfortunately, in regions with few cases, this can end up creating strings of 0 days (this is an exceptional example). The alternative would be to have -10 cases on this day...which would also mess up patterns.

If you'd like the "cleanest" version of the case data, you can use the Alberta case CSV (under "Data Export"):

https://www.alberta.ca/stats/covid-19-alberta-statistics.htm

Note that while the CSV can be used to reconstruct regional case time series, it cannot be used to reconstruct a regional mortality/recovered time series.

I should add a note to the README (#82) to mention this issue.

Hope this helps.
