### ISSUE TITLE
Halimand-Norfolk

### ISSUE THREAD

**Issue by Paracutin1** [ccodwg/Covid19Canada#96]
why has Halimand-Norfolk region not reported any new cases in weeks? I know there is a testing shortage but they should be reporting something?

**Comment by jeanpaulrsoucy** [comment]
Thanks for the message. It looked like H-N archived most of their COVID data on January 7, but since it didn't break our data pipeline, I didn't notice until you pointed it out.

https://hnhu.org/additional-daily-statistics/

Their dashboard is now useless for our purposes, since there is no way to continue reporting cases, mortality and recovered in the same format as before. A few PHUs have done this in response to testing limitations in 2022. I'm going to have to swap out their dataset for the Ministry of Health dataset. Stay tuned for that after tonight's update---you'll see a full time series for this PHU again.
